# Generated by Django 5.2.3 on 2025-09-18 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_user_alter_category_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='register_at',
            field=models.DateField(default=datetime.datetime(2025, 9, 18, 15, 24, 5, 937618, tzinfo=datetime.timezone.utc)),
        ),
    ]
