# Generated by Django 5.2.3 on 2025-09-21 05:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_user_register_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='register_at',
            field=models.DateField(default=datetime.datetime(2025, 9, 21, 5, 38, 41, 205924, tzinfo=datetime.timezone.utc)),
        ),
    ]
