# Generated by Django 5.2.3 on 2025-09-21 05:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_alter_user_register_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='time',
            field=models.TimeField(default=datetime.datetime(2025, 9, 21, 5, 43, 46, 687536, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='income',
            name='time',
            field=models.TimeField(default=datetime.datetime(2025, 9, 21, 5, 43, 46, 686537, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='register_at',
            field=models.DateField(default=datetime.datetime(2025, 9, 21, 5, 43, 46, 682518, tzinfo=datetime.timezone.utc)),
        ),
    ]
