# Generated by Django 5.2.3 on 2025-09-21 05:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_expense_time_income_time_alter_user_register_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='time',
            field=models.TimeField(default=datetime.time(5, 52, 14, 353419)),
        ),
        migrations.AlterField(
            model_name='income',
            name='time',
            field=models.TimeField(default=datetime.datetime(2025, 9, 21, 5, 52, 14, 352423, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='register_at',
            field=models.DateField(default=datetime.datetime(2025, 9, 21, 5, 52, 14, 351409, tzinfo=datetime.timezone.utc)),
        ),
    ]
