# Generated by Django 5.2.3 on 2025-09-21 06:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_alter_transaction_source_alter_transaction_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='time',
        ),
        migrations.RemoveField(
            model_name='income',
            name='time',
        ),
        migrations.AlterField(
            model_name='user',
            name='register_at',
            field=models.DateField(default=datetime.datetime(2025, 9, 21, 6, 26, 59, 306295, tzinfo=datetime.timezone.utc)),
        ),
    ]
