# Generated by Django 5.2.3 on 2025-09-23 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_alter_user_register_at_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='register_at',
            field=models.DateField(default=datetime.datetime(2025, 9, 23, 18, 4, 32, 72817, tzinfo=datetime.timezone.utc)),
        ),
    ]
