# Generated by Django 5.2.7 on 2025-10-05 10:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_alter_user_register_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='register_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
